[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloth-tools"
version = "0.0.2"
authors = [
  { name="Victor-Louis De Gusseme", email="victorlouisdg@gmail.com" },
]
description = "Official package for the ICRA 2024 Cloth Competition"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy",
    "click",
    "airo-typing @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-typing",
    "airo-robots @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-robots"
]

[project.urls]
Homepage = "https://github.com/Victorlouisdg/cloth-competition"
Issues = "https://github.com/Victorlouisdg/cloth-competition/issues"